apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-nextcloud
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi